build:
  maxIssues: 5
  weights:
    formatting: 6 # maxIssues + 1 so formatting issues will always fail

console-reports:
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    #  - 'FindingsReport'
    - 'FileBasedFindingsReport'
    - 'LiteFindingsReport'



performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

complexity:
  LongMethod:
    threshold: 80