config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'IssuesReport'
    - 'FileBasedIssuesReport'
  #  - 'LiteIssuesReport'

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

complexity:
  LongMethod:
    allowedLines: 90

Compose:
  ModifierMissing:
    active: false